baseurl: "https://monohue.net"
githuburl: "https://github.com/Monohue/Melchior"
name: Melchior
slogan: Exploring the very nature of science.
description: MonoHue's Blog.
paginate: 10
paginate_path: "page:num"
excerpt_separator:  "<!-- more -->"
websuffix: " - Melchior"
lighttheme: "light"
darktheme: "dark"
