baseurl: "http://blog.magi.red"
name: Melchior
slogan: Exploring the very nature of science.
description: MonoHue's Blog.
paginate: 10
paginate_path: "page:num"
excerpt_separator:  "<!-- more -->"
websuffix: " - Melchior"
